### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by jhawk28** [gagliardetto/solana-go#187]
some transactions are causing the library to panic at: github.com/gagliardetto/solana-go@v1.9.3/transaction.go:490

**Comment by gagliardetto** [comment]
Hi 

can you please post the whole panic trace?

**Comment by gagliardetto** [comment]
It would also be useful to have one of these transactions that cause the panic.

**Comment by jhawk28** [comment]
```
panic: runtime error: makeslice: len out of range
goroutine 3107636 [running]:
github.com/gagliardetto/solana-go.(*Transaction).UnmarshalWithDecoder(0xc052ed05a0, 0xc023e44d20)
        /Users/joshua/go/pkg/mod/github.com/gagliardetto/solana-go@v1.9.3/transaction.go:490 +0x7c
github.com/gagliardetto/binary.(*Decoder).decodeBin(0xc023e44d20, {0x0, 0x0, 0x0}, 0x0?)
        /Users/joshua/go/pkg/mod/github.com/gagliardetto/binary@v0.7.9/decoder_bin.go:84 +0x10ec
github.com/gagliardetto/binary.(*Decoder).decodeWithOptionBin(0x0?, {0x10f7f60?, 0xc05b9931f8?}, 0x412005?)
        /Users/joshua/go/pkg/mod/github.com/gagliardetto/binary@v0.7.9/decoder_bin.go:37 +0x105
github.com/gagliardetto/binary.(*Decoder).Decode(0xc008228230?, {0x10f7f60?, 0xc05b9931f8?})
        /Users/joshua/go/pkg/mod/github.com/gagliardetto/binary@v0.7.9/decoder.go:130 +0x52
github.com/gagliardetto/solana-go.TransactionFromDecoder(...)
        /Users/joshua/go/pkg/mod/github.com/gagliardetto/solana-go@v1.9.3/transaction.go:83
```

**Comment by jhawk28** [comment]
I don't have a transaction that is causing the issue yet. If can get find one, I'll post.

**Comment by gagliardetto** [comment]
Try github.com/gagliardetto/solana-go@v1.10.0

**Comment by gagliardetto** [comment]
Closing as stale
