### ISSUE TITLE
DecodeInstruction: out of memory error

### ISSUE THREAD

**Issue by tclairet** [gagliardetto/solana-go#81]
Hi,

I have a backend that parse every transaction and noticed unexpected out of memory errors. After some investigation, I tracked it down to one tx (there are others). You can check that tx [here](https://explorer.solana.com/tx/5czZjwP8hX8F6K83Wky2mM5jC1tgiMwBhxsomCxxCcnjk1nzxBaNuqnGrnkdixGBQQ2fU2SkroNAa5ia7ALmDMR).

Here 's a test case that reproduce the issue.

```go
func TestDecodeInstructionOutOfMemory(t *testing.T) {
	client := rpc.New(rpc.MainNetBetaSerum_RPC)

	txSig, err := solana.SignatureFromBase58("5czZjwP8hX8F6K83Wky2mM5jC1tgiMwBhxsomCxxCcnjk1nzxBaNuqnGrnkdixGBQQ2fU2SkroNAa5ia7ALmDMR")
	if err != nil {
		t.Fatal(err)
	}
	txRaw, err := client.GetTransaction(context.Background(), txSig, nil)
	if err != nil {
		t.Fatal(err)
	}

	tx := txRaw.Transaction.GetParsedTransaction()
	instruction := tx.Message.Instructions[2] // this the instruction causing the issue

	var accounts []*solana.AccountMeta
	for _, account := range instruction.Accounts {
		accounts = append(accounts, &solana.AccountMeta{
			PublicKey: tx.Message.AccountKeys[account],
		})
	}

	if _, err := system.DecodeInstruction(accounts, instruction.Data); err != nil {
		t.Fatal(err)
	}
}
```

And here's the relevant dump trace part

```
runtime: out of memory: cannot allocate 140754945048576-byte block (7569408 in use)
fatal error: out of memory

goroutine 52 [running]:
runtime.throw({0x10326cc44, 0xd})
	/usr/local/go/src/runtime/panic.go:1198 +0x54 fp=0x14000153150 sp=0x14000153120 pc=0x102813e44
runtime.(*mcache).allocLarge(0x1044305b8, 0x8004107a53c0, 0x0, 0x1)
	/usr/local/go/src/runtime/mcache.go:229 +0x2f4 fp=0x140001531b0 sp=0x14000153150 pc=0x1027f3324
runtime.mallocgc(0x8004107a53c0, 0x10360dca0, 0x1)
	/usr/local/go/src/runtime/malloc.go:1082 +0x5ac fp=0x14000153240 sp=0x140001531b0 pc=0x1027e943c
runtime.makeslice(0x10360dca0, 0x8004107a53c0, 0x8004107a53c0)
	/usr/local/go/src/runtime/slice.go:98 +0x90 fp=0x14000153270 sp=0x14000153240 pc=0x10282d700
github.com/gagliardetto/binary.readNBytes(0x8004107a53c0, {0x1037ca190, 0x1400015a960})
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/decoder.go:273 +0x38 fp=0x140001532b0 sp=0x14000153270 pc=0x102e1a138
github.com/gagliardetto/binary.(*Decoder).ReadNBytes(...)
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/decoder.go:286
github.com/gagliardetto/binary.(*Decoder).ReadRustString(0x1400015a960)
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/decoder.go:548 +0x74 fp=0x14000153370 sp=0x140001532b0 pc=0x102e1c924
github.com/gagliardetto/solana-go/programs/system.(*AllocateWithSeed).UnmarshalWithDecoder(0x140001c3240, 0x1400015a960)
	/Users/XX/go/pkg/mod/github.com/gagliardetto/solana-go@v1.4.1-0.20220616103316-ad739fd566b3/programs/system/AllocateWithSeed.go:212 +0x74 fp=0x140001533b0 sp=0x14000153370 pc=0x102ffa2b4
github.com/gagliardetto/binary.(*Decoder).decodeBin(0x1400015a960, {0x103775820, 0x140001c3240, 0x16}, 0x0)
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/decoder_bin.go:83 +0x628 fp=0x14000153710 sp=0x140001533b0 pc=0x102e1db98
github.com/gagliardetto/binary.(*Decoder).decodeWithOptionBin(0x1400015a960, {0x103775820, 0x140001c3240}, 0x0)
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/decoder_bin.go:36 +0x1a8 fp=0x14000153780 sp=0x14000153710 pc=0x102e1d528
github.com/gagliardetto/binary.(*Decoder).Decode(0x1400015a960, {0x103775820, 0x140001c3240})
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/decoder.go:121 +0xc4 fp=0x140001537e0 sp=0x14000153780 pc=0x102e19064
github.com/gagliardetto/binary.(*BaseVariant).UnmarshalBinaryVariant(0x1400034f260, 0x1400015a960, 0x140005486c0)
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/variant.go:389 +0x45c fp=0x140001538e0 sp=0x140001537e0 pc=0x102e351ac
github.com/gagliardetto/solana-go/programs/system.(*Instruction).UnmarshalWithDecoder(0x1400034f260, 0x1400015a960)
	/Users/XX/go/pkg/mod/github.com/gagliardetto/solana-go@v1.4.1-0.20220616103316-ad739fd566b3/programs/system/instructions.go:190 +0x44 fp=0x14000153920 sp=0x140001538e0 pc=0x103003374
github.com/gagliardetto/binary.(*Decoder).decodeBin(0x1400015a960, {0x10373f560, 0x1400034f260, 0x16}, 0x0)
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/decoder_bin.go:83 +0x628 fp=0x14000153c80 sp=0x14000153920 pc=0x102e1db98
github.com/gagliardetto/binary.(*Decoder).decodeWithOptionBin(0x1400015a960, {0x10373f560, 0x1400034f260}, 0x0)
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/decoder_bin.go:36 +0x1a8 fp=0x14000153cf0 sp=0x14000153c80 pc=0x102e1d528
github.com/gagliardetto/binary.(*Decoder).Decode(0x1400015a960, {0x10373f560, 0x1400034f260})
	/Users/XX/go/pkg/mod/github.com/gagliardetto/binary@v0.6.1/decoder.go:121 +0xc4 fp=0x14000153d50 sp=0x14000153cf0 pc=0x102e19064
github.com/gagliardetto/solana-go/programs/system.DecodeInstruction({0x140001c3200, 0x8, 0x8}, {0x14000344539, 0x9e, 0x103})
	/Users/XX/go/pkg/mod/github.com/gagliardetto/solana-go@v1.4.1-0.20220616103316-ad739fd566b3/programs/system/instructions.go:211 +0x74 fp=0x14000153db0 sp=0x14000153d50 pc=0x1030035e4
github.com/XX/XX.TestDecodeInstructionOutOfMemory(0x14000220d00)
	/Users/XX/test.go:xx +0x300 fp=0x14000153f70 sp=0x14000153db0 pc=0x103143590
testing.tRunner(0x14000220d00, 0x1037aae18)
	/usr/local/go/src/testing/testing.go:1259 +0x104 fp=0x14000153fc0 sp=0x14000153f70 pc=0x1028e8714
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1133 +0x4 fp=0x14000153fc0 sp=0x14000153fc0 pc=0x1028496d4
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x328
```

**Comment by gagliardetto** [comment]
Hey

The instruction you're trying to decode seems to **not be** a system-program instruction. Hence the OOM.

**Comment by tclairet** [comment]
Thanks, I actually missed that. After your comment, I found 
https://github.com/gagliardetto/solana-go/blob/main/transaction.go#L457
```go
progKey, err := tx.ResolveProgramIDIndex(inst.ProgramIDIndex)
if err == nil {
	accounts := inst.ResolveInstructionAccounts(&tx.Message)
	decodedInstruction, err := DecodeInstruction(progKey, accounts, inst.Data)
	....
```
It could be useful to use that in the main readme rather than 

```go

inst, err := system.DecodeInstruction(i0.ResolveInstructionAccounts(&tx.Message), i0.Data)

// OR

decodedInstruction, err := solana.DecodeInstruction(
      system.ProgramID,
      i0.ResolveInstructionAccounts(&tx.Message),
      i0.Data,
)
```

**Comment by gagliardetto** [comment]
Updated the README. Thanks!
